[package]
name = "perkele-shared"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
rrule = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
